version: "3"
services:
  vue-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn serve
